spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/faculdade?useSSL=false
    username: root
    password: Developer123
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never # Desabilitado - usando Flyway para migrações e dados iniciais

  defer-datasource-initialization: true